language: csharp
mono: none
dotnet: 2.0.0
dist: trusty
sudo: required
solution: VideoMenuRest.sln
before_script:
  - chmod +x build.sh
 script:
  - ./build.sh
install:
- dotnet restore
script:
- dotnet build
branches:
  only:
  - master