language: csharp
dist: trusty
mono: none
sudo: required
dotnet: 2.0.0
solution: VideoMenuRest.sln
branches:
  only:
  - master
install:
- dotnet restore
script:
- dotnet build
- dotnet clean -c Release
- dotnet build VideoMenuRest.sln -c Release